name: molt-action

description: Keep your Deno projects up-to-date with jsr.io/@molt

branding:
  icon: 'refresh-cw'
  color: 'gray-dark'

inputs:
  config:
    description: Relative path to your Deno configuration file from the project root
    required: false
    default: deno.json{,c}

  root:
    description: Root directory of your project
    required: true
    default: ./

  source:
    description: Glob patterns to match source files
    required: true
    default: deno.json{,c}

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash

runs:
  using: composite

  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.deno
          ~/.cache/deno
          ~/Library/Caches/deno
          ~/AppData/Local/deno
        key: molt-action-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('deno.lock') }}
        restore-keys: |
          molt-action-${{ runner.arch }}-${{ runner.os }}

    - name: Cache dependencies
      run: deno task cache

    - name: Run main script
      run: deno task run
