name: molt-action

description: Create a pull request to update dependencies with jsr.io/@molt

branding:
  icon: 'refresh-cw'
  color: 'gray-dark'

inputs:
  commit:
    description: Whether to commit changes to the local git repository.
    required: false
    default: true

  commit-prefix:
    description: >
      Prefix for commit messages. Defaults to `chore` if the repository
      follows Conventional Commits, otherwise none.
    required: false

  group-by:
    description: >
      Create a single pull request for each specified group. The value must be
      `dependency`, or unspecified. Other options such as `package` and `repository`
      may be supported in the future.
    required: false

  resolve-imports:
    description: Resolve local imports to find dependencies recursively.
    required: false
    default: false

  pull-request:
    description: >
      Whether to create a pull request to update dependencies.
    required: false
    default: true

  root:
    description: >
      Root directory of the relevant source files. Defaults to the shallowest
      directory containing `deno.json` or `deno.jsonc` if available, otherwise
      the repository root.
    required: false

  source:
    description: >
      Glob patterns to match source files. Defaults to `deno.json{,c}` if
      available with imports, otherwise `**/*.ts`.
    required: false

outputs:
  dependencies:
    description: A JSON list of updated dependencies.
    value: ${{ steps.main.outputs.dependencies }}

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash

runs:
  using: composite

  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.deno
          ~/.cache/deno
          ~/Library/Caches/deno
          ~/AppData/Local/deno
        key: molt-action-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('deno.lock') }}
        restore-keys: |
          molt-action-${{ runner.arch }}-${{ runner.os }}

    - name: Cache dependencies
      run: deno task cache

    - id: main
      name: Run main script
      run: deno task run
