name: molt-action

description: Create a pull request to update dependencies with jsr.io/@molt

branding:
  icon: 'refresh-cw'
  color: 'gray-dark'

inputs:
  author:
    description: >
      Author of the pull request in the format of `Display Name <email@adress.com>`.
    default: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>

  commit:
    description: Whether to commit changes locally.
    default: true

  commit-prefix:
    description: Prefix for commit messages.
    default: 'chore:'

  committer:
    description: >
      Name of the committer in the format of `Display Name <email@address.com>`
    default: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

  pull-request:
    description: Whether to create a pull request.
    default: true

  resolve-imports:
    description: Resolve local imports to find dependencies recursively.
    default: false

  root:
    description: >
      Root directory of the relevant source files. Defaults to the shallowest
      directory containing `deno.json` or `deno.jsonc` if available, otherwise
      the repository root.

  source:
    description: >
      Glob patterns to match source files. Defaults to `deno.json{,c}` if
      available with imports, otherwise `**/*.ts`.

outputs:
  dependencies:
    description: A JSON list of updated dependencies.
    value: ${{ steps.main.outputs.dependencies }}

  summary:
    description: A summary of the changes made.
    value: ${{ steps.main.outputs.summary }}

  report:
    description: A detailed report of the changes made in Markdown format.
    value: ${{ steps.main.outputs.report }}

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash

runs:
  using: composite

  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.deno
          ~/.cache/deno
          ~/Library/Caches/deno
          ~/AppData/Local/deno
        key: molt-action-${{ runner.arch }}-${{ runner.os }}-${{ hashFiles('deno.lock') }}
        restore-keys: |
          molt-action-${{ runner.arch }}-${{ runner.os }}

    - name: Cache dependencies
      run: deno task cache

    - id: main
      name: Run main script
      run: deno task run

    - name: Create a pull request
      uses: peter-evans/create-pull-request@v6
      if: inputs.pull-request == 'true'
      with:
        author: ${{ inputs.author }}
        commiter: ${{ inputs.committer }}
