name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: hasundue/actions/.github/workflows/test-deno.yml@main
  integration:
    uses: ./.github/workflows/integration.yml
