name: integration

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run molt-action
        id: action
        uses: ./
        with:
          cache-key-suffix: ${{ hashFiles('deno.lock') }}
          pull-request: false
          root: 'test/fixtures'
          script: 'main.ts'

      - name: Check updated dependencies
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.dependencies }}
          expected: '["@luca/flag","deno.land/std"]'

      - name: Check updated files
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.files }}
          expected: '["deno.json","deno.lock"]'

      - name: Check summary
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.summary }}
          expected: 'chore: update @luca/flag and deno.land/std'

      - name: Check report
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.report }}
          expected: '#### :package: @luca/flag [1.0.0](https://jsr.io/@luca/flag/1.0.0)'
          comparison: startsWith

  test-ts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run molt-action
        id: action
        uses: ./
        with:
          cache-key-suffix: ${{ hashFiles('deno.lock') }}
          config: false
          pull-request: false
          root: 'test/fixtures'
          script: 'main.ts'

      - name: Check updated dependencies
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.dependencies }}
          expected: '["@std/assert","@std/collections"]'

      - name: Check updated files
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.files }}
          expected: '["deno.lock","mod.ts","mod_test.ts"]'

      - name: Check summary
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.summary }}
          expected: 'chore: update @std/assert and @std/collections'

      - name: Check report
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.report }}
          expected: '#### :package: @std/assert [0.224.0](https://jsr.io/@std/assert/0.224.0) → '
          comparison: startsWith

