name: integration

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  runs-on: ubuntu-latest

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: action
        uses: ./
        with:
          commit: false
          pull-request: false
          root: test/fixtures

      - uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.updated }}
          expected: '["@molt/cli","@molt/core"]'

      - uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.summary }}
          expected: 'chore: update @molt/cli and @molt/core'

      - uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.report }}
          expected: |
            ### @molt/cli [0.18.0](https://jsr.io/@molt/cli/0.18.0) → [0.18.4](https://jsr.io/@molt/cli/0.18.4)

            <details>

            <summary>2 bug fixes</summary>

            ### :bug: Bug Fixes:

            - better error messages on unresolved deps
            - bump @molt/core to 0.18.4

            </details>

            ### :package: @molt/core [0.18.0](https://jsr.io/@molt/core/0.18.0) → [0.18.4](https://jsr.io/@molt/core/0.18.4)

            <details>

            <summary>4 bug fixes</summary>

            ### :bug: Bug Fixes:

            - use `jsr:@deno/graph` for `x/deno_graph`
            - do not throw on unresolved deps (#166)
            - resolve mapped jsr imports with subpath
            - handle identical dependencies correctly

            </details>
