name: integration

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  runs-on: ubuntu-latest

jobs:
  action:
    runs-on: ubuntu-latest

    outputs:
      dependencies: ${{ steps.action.outputs.dependencies }}

    steps:
      - uses: actions/checkout@v4

      - id: action
        uses: ./
        with:
          commit: false
          pull-request: false
          root: test/fixtures

      - uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.summary }}
          expected: 'chore: bump @molt/core to '
          comparison: startsWith

  check:
    needs: action
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dependency: ${{ fromJSON(needs.action.outputs.dependencies) }}

    steps:
      - uses: nick-fields/assert-action@v2
        with:
          actual: ${{ matrix.dependency }}
          expected: '@molt/core'
