name: integration

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run molt-action
        id: action
        uses: ./
        with:
          cache-key-suffix: ${{ hashFiles('deno.lock') }}
          commit: false
          pull-request: false
          script: 'main.ts'
          root: 'test/fixtures'

      - name: Check updated dependencies
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.updated }}
          expected: '["@actions/core","@molt/core","deno.land/x/hono"]'

      - name: Check summary
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.summary }}
          expected: 'chore: update dependencies'

      - name: Check report
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.report }}
          expected: '#### :package: @actions/core [1.10.0](https://www.npmjs.com/package/@actions/core/v/1.10.0) → '
          comparison: startsWith

  test-ts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run molt-action
        id: action
        uses: ./
        with:
          cache-key-suffix: ${{ hashFiles('deno.lock') }}
          commit: false
          pull-request: false
          script: 'main.ts'
          root: 'test/fixtures'
          source: '**/*.ts'

      - name: Check updated dependencies
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.updated }}
          expected: '["@std/assert","@std/collections"]'

      - name: Check summary
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.summary }}
          expected: 'chore: update @std/assert and @std/collections'

      - name: Check report
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.report }}
          expected: '#### :package: @std/assert [0.224.0](https://jsr.io/@std/assert/0.224.0) → '
          comparison: startsWith

