name: integration

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: action
        uses: ./
        with:
          commit: false
          pull-request: false
          root: test/fixtures
          script: ./main.ts

      - uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.updated }}
          expected: '["@actions/core","@molt/core","deno.land/x/hono"]'

      - uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.summary }}
          expected: 'chore: update dependencies'

      - uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.action.outputs.report }}
          expected: '### :package: @actions/core [1.10.0](https://www.npm.js/package/@actions/core/v/1.10.0) → '
          comparison: startsWith
